[2024-05-14, 02:26:59 UTC] {pod_manager.py:483} INFO - [base] bash: line 2:     7 Killed                  
stellar-etl export_operations -s 185224 -e 300329 -o dag-exported/scheduled__2024-02-25T00:00:00+00:00/185224-300329-operations.txt 
--cloud-storage-bucket us-central1-test-hubble-2-5f1f2dbf-bucket --cloud-provider gcp 
-u 'batch_id=scheduled__2024-02-25T00:00:00+00:00-backfill,batch_run_date=2024-02-18 00:00:00,batch_insert_ts=2024-05-14T02:24:57Z' 
--testnet --datastore-path sdf-ledger-close-metas/ledgers --strict-export 2>> stderr.out

[2024-05-14, 02:26:59 UTC] {pod_manager.py:718} INFO - Checking if xcom sidecar container is started.
[2024-05-14, 02:26:59 UTC] {pod_manager.py:721} INFO - The xcom sidecar container is started.
[2024-05-14, 02:26:59 UTC] {pod_manager.py:798} INFO - Running command... if [ -s /airflow/xcom/return.json ]; then cat /airflow/xcom/return.json; else echo __airflow_xcom_result_empty__; fi
[2024-05-14, 02:28:15 UTC] {pod_manager.py:798} INFO - Running command... kill -s SIGINT 1
[2024-05-14, 02:29:31 UTC] {pod.py:559} INFO - xcom result file is empty.
[2024-05-14, 02:29:31 UTC] {pod_manager.py:616} INFO - Pod export-operations-task-njng7qlx has phase Running
[2024-05-14, 02:29:33 UTC] {pod_manager.py:616} INFO - Pod export-operations-task-njng7qlx has phase Running
[2024-05-14, 02:29:35 UTC] {pod.py:909} INFO - Deleting pod: export-operations-task-njng7qlx
[2024-05-14, 02:29:35 UTC] {taskinstance.py:1826} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 570, in execute
    return self.execute_sync(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 629, in execute_sync
    self.cleanup(
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 839, in cleanup
    raise AirflowException(
airflow.exceptions.AirflowException: Pod export-operations-task-njng7qlx returned a failure.
remote_pod: {'api_version': 'v1',